# docker-compose.yml

version: '3.8'

services:

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-site
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - flask
    networks:
      - my-project

  flask:
    build:
      context: ./flask_service
      dockerfile: Dockerfile
    container_name: portfolio-site-services
    ports:
      - "5001:5001"
    networks:
      - my-project

networks:
  my-project:
    driver: bridge
